use_default_settings: true
general:
  debug: false
search:
  default_lang: zh-CN
  formats:
    - html
    - json
server:
  limiter: false
  image_proxy: false
outgoing:
  request_timeout: 5.0
  max_request_timeout: 8.0
