param(
  [string] $Path = ".env"
)

$ErrorActionPreference = "Stop"

function Get-EnvValue {
  param(
    [Parameter(Mandatory = $true)]
    [string] $Content,

    [Parameter(Mandatory = $true)]
    [string] $Name
  )

  $match = [regex]::Match($Content, "(?m)^$([regex]::Escape($Name))=(.+)$")
  if ($match.Success) {
    return $match.Groups[1].Value.Trim()
  }
  return $null
}

$resolvedPath = (Resolve-Path -LiteralPath $Path).Path
$content = [System.IO.File]::ReadAllText($resolvedPath, [System.Text.Encoding]::UTF8)
$postgresPassword = Get-EnvValue -Content $content -Name "POSTGRES_PASSWORD"
$postgresUser = Get-EnvValue -Content $content -Name "POSTGRES_USER"
$postgresDatabase = Get-EnvValue -Content $content -Name "POSTGRES_DB"

if ([string]::IsNullOrWhiteSpace($postgresPassword) -or $postgresPassword -match 'change-this-local-database-password|edunova_dev_password') {
  throw "POSTGRES_PASSWORD must be initialized before PostgreSQL can be synchronized."
}
if ($postgresPassword -notmatch '^[A-Za-z0-9_-]+={0,2}$') {
  throw "POSTGRES_PASSWORD must use the URL-safe Base64 format generated by initialize_env.ps1."
}

if ([string]::IsNullOrWhiteSpace($postgresUser)) {
  $postgresUser = "edunova"
}
if ([string]::IsNullOrWhiteSpace($postgresDatabase)) {
  $postgresDatabase = "edunova"
}
if ($postgresUser -notmatch '^[A-Za-z_][A-Za-z0-9_]*$' -or $postgresDatabase -notmatch '^[A-Za-z_][A-Za-z0-9_]*$') {
  throw "POSTGRES_USER and POSTGRES_DB must be PostgreSQL identifiers."
}

& docker compose up -d postgres
if ($LASTEXITCODE -ne 0) {
  throw "PostgreSQL could not be started."
}

& docker compose exec -T postgres psql -v ON_ERROR_STOP=1 -U $postgresUser -d $postgresDatabase -c "ALTER ROLE $postgresUser WITH PASSWORD '$postgresPassword';"
if ($LASTEXITCODE -ne 0) {
  throw "PostgreSQL role password synchronization failed."
}

Write-Host "Local PostgreSQL role password synchronized."
